### ISSUE TITLE
[Request] Dark mode theme

### ISSUE THREAD

**Issue by rodrigore** [dracula/qutebrowser#1]
Can you make something like solarized dark all ? https://github.com/alphapapa/solarized-everything-css/blob/master/css/solarized-dark/solarized-dark-all-sites.css

I want a dark mode using the colors of dracula.

**Comment by apercova** [comment]
Hi @rodrigore 
Why don't getting some fun by crafting it in you own. It could be a great contribution to Dracula community?.
https://github.com/dracula/dracula-theme#are-you-going-to-support-editor-x
https://github.com/dracula/dracula-theme#how-do-i-submit-a-new-theme
