### ISSUE TITLE
Letters don't show up in hint mode

### ISSUE THREAD

**Issue by black-purple** [dracula/qutebrowser#13]
I installed the ```dracula``` theme for ```qutebrowser``` but now the letters in the hints when pressing ```f``` don't show up.

Preview image to show the issue.

![2021-06-25-180421_1366x768_scrot](https://user-images.githubusercontent.com/82895430/123460868-3431c680-d5e0-11eb-8024-81baa46f0821.png)

**Comment by The-Compiler** [comment]
If you quit qutebrowser and run with `--debug --loglevel vdebug`, can you show what it says after the `VDEBUG   config     stylesheet:register:112 stylesheet for MainWindow: ` line?

**Comment by black-purple** [comment]
> If you quit qutebrowser and run with `--debug --loglevel vdebug`, can you show what it says after the `VDEBUG config stylesheet:register:112 stylesheet for MainWindow: ` line?

I can't find this line in the output.
