### ISSUE TITLE
Permission Denied (publickey)

### ISSUE THREAD

**Issue by dssecret** [dracula/qutebrowser#2]
When I clone this repository, it gives me an error.
```
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by The-Compiler** [comment]
Try using https to clone instead (and make sure you don't have a typo in the repo name).

**Comment by dssecret** [comment]
I tried it with `git clone https://github.com/evannagle/qutebrowser-dracula-theme.git dracula` and it worked, so the README should be changed to use https when cloning this repo. @evannagle needs to fix it.
