### ISSUE TITLE
Move to official org?

### ISSUE THREAD

**Issue by zenorocha** [dracula/qutebrowser#4]
Hey @evannagle,

This is Zeno, creator of Dracula. I just this found repo, good job on that!

I'm wondering if you would like to have this become an official theme in our [Dracula organization](https://github.com/dracula)?

Let me know what you think.

**Comment by evannagle** [comment]
Hey @zenorocha -- hey, that's great news! I'd be honored. Let me know if you need anything from me to make that happen.

**Comment by zenorocha** [comment]
That's awesome! I just invited you to the org, so know all you have to do is:
1. Accept GitHub invitation
2. Transfer the repository
3. Apply the same format used on https://github.com/dracula/template

The last step is important because it will be used to auto-generate the site. Especially the `screenshot.png` and `INSTALL.md` files.

Let me know if you have any questions

**Comment by evannagle** [comment]
Hey Zeno — looks like my org invite got cancelled?

**Comment by zenorocha** [comment]
I added you on the wrong team, that's why I needed to cancel, but I thought the first invitation I sent was still valid. Anyways, I added you again, let's try now.

**Comment by evannagle** [comment]
Hey @zenorocha -- just followed the ol' instructions and got everything setup. Let me know if there's anything else you need, and again, thanks for all of your great work!

**Comment by The-Compiler** [comment]
Yay! I [updated the link](https://github.com/qutebrowser/qutebrowser/commit/51c02386cb4af6c201b1faede6f4b1b94422552b) in qutebrowser's documentation.

**Comment by zenorocha** [comment]
It's live in the site! Thanks @The-Compiler ;)

https://draculatheme.com/qutebrowser

**Comment by The-Compiler** [comment]
I'm a bit confused by the install instructions - see #5.
