### ISSUE TITLE
Font family settings

### ISSUE THREAD

**Issue by The-Compiler** [dracula/qutebrowser#6]
qutebrowser v1.10.0 [will change](https://github.com/qutebrowser/qutebrowser/blob/master/doc/changelog.asciidoc) how the default font family is set.

Thus, this theme will need some adjustments (especially if you want it to work with both older and newer versions). However, this makes me wonder: Why does it set the font family/size at all?

**Comment by evannagle** [comment]
It probably shouldn't. I'll go ahead and remove.
