### ISSUE TITLE
Dark background

### ISSUE THREAD

**Issue by quantum-booty** [dracula/qutebrowser#9]
How do I enable dark backgrounds? Only the terminal is dark for me.

**Comment by The-Compiler** [comment]
What terminal?

**Comment by quantum-booty** [comment]
![image](https://user-images.githubusercontent.com/28958399/92286531-3f0b5580-eeff-11ea-985b-eb068f4c25d9.png)
The background is still white, sorry if I'm misunderstanding something, I thought this dark theme would make the webpages dark aswell.

**Comment by The-Compiler** [comment]
No, this is just a theme for qutebrowser's user interface.

To get dark websites, you can:

- Set `colors.webpage.darkmode.enabled` if you have Qt >= 5.14 (but it sometimes doesn't work properly and requires a restart of qutebrowser to toggle)
- Set `colors.webpage.prefers_color_scheme_dark` if you have Qt >= 5.14 (but it only asks websites for a dark color scheme, so it only works with sites which support it)
- Use `content.user_stylesheets` and e.g. the [Solarized everything CSS](https://github.com/alphapapa/solarized-everything-css/)

**Comment by quantum-booty** [comment]
Thank you very much, that very helpful! Thank you for creating this amazing browser :)
